name: Build and Deploy to Azure VM

on:
  push:
    branches:
      - main   # change to your branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Build JAR (Maven example)
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Copy JAR to Azure VM
      - name: Copy JAR to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          source: "target/keystone-shaded.jar"
          target: "/home/${{ secrets.AZURE_VM_USER }}/app/keystone.jar"

      # 5. SSH into VM and run JAR
      - name: Run JAR on Azure VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.AZURE_VM_USER }}/app
            pkill -f 'java -jar' || true
            nohup java -jar keystone-shaded.jar > app.log 2>&1 &